spring:
  application:
    name: hello-spring

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # SQL을 한 줄이 아닌 보기 좋게 포맷팅해서 출력
